// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Scheduling_links
{
    /// <summary>Resource type (currently, this is always EventType)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Scheduling_linksPostResponse_resource_owner_type
    {
        [EnumMember(Value = "EventType")]
        #pragma warning disable CS1591
        EventType,
        #pragma warning restore CS1591
    }
}
