// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Outgoing_communications
{
    /// <summary>
    /// Object for an Email communication
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Outgoing_communicationsGetResponse_collectionMember2 : IParsable
    {
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The UTC date and time when the email message was created (format: &quot;2020-01-02T03:04:05.678123Z&quot;)</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The event_type_uri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventTypeUri { get; set; }
#nullable restore
#else
        public string EventTypeUri { get; set; }
#endif
        /// <summary>The event_uri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventUri { get; set; }
#nullable restore
#else
        public string EventUri { get; set; }
#endif
        /// <summary>The from property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>The scheduling_url property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SchedulingUrl { get; set; }
#nullable restore
#else
        public string SchedulingUrl { get; set; }
#endif
        /// <summary>The sender_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderEmail { get; set; }
#nullable restore
#else
        public string SenderEmail { get; set; }
#endif
        /// <summary>The sender_uri property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SenderUri { get; set; }
#nullable restore
#else
        public string SenderUri { get; set; }
#endif
        /// <summary>The UTC date and time when the email message was sent (format: &quot;2020-01-02T03:04:05.678123Z&quot;)</summary>
        public DateTimeOffset? SentAt { get; set; }
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? To { get; set; }
#nullable restore
#else
        public string To { get; set; }
#endif
        /// <summary>The type property</summary>
        public global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse_collectionMember2_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse_collectionMember2"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse_collectionMember2 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse_collectionMember2();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "body", n => { Body = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "event_type_uri", n => { EventTypeUri = n.GetStringValue(); } },
                { "event_uri", n => { EventUri = n.GetStringValue(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "scheduling_url", n => { SchedulingUrl = n.GetStringValue(); } },
                { "sender_email", n => { SenderEmail = n.GetStringValue(); } },
                { "sender_uri", n => { SenderUri = n.GetStringValue(); } },
                { "sent_at", n => { SentAt = n.GetDateTimeOffsetValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "to", n => { To = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse_collectionMember2_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("body", Body);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("event_type_uri", EventTypeUri);
            writer.WriteStringValue("event_uri", EventUri);
            writer.WriteStringValue("from", From);
            writer.WriteStringValue("scheduling_url", SchedulingUrl);
            writer.WriteStringValue("sender_email", SenderEmail);
            writer.WriteStringValue("sender_uri", SenderUri);
            writer.WriteDateTimeOffsetValue("sent_at", SentAt);
            writer.WriteStringValue("subject", Subject);
            writer.WriteStringValue("to", To);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse_collectionMember2_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
