// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Calendly.OpenApiClient.Outgoing_communications
{
    /// <summary>
    /// Builds and executes requests for operations under \outgoing_communications
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Outgoing_communicationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Outgoing_communicationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/outgoing_communications?organization={organization}{&count*,max_created_at*,min_created_at*,page_token*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Outgoing_communicationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/outgoing_communications?organization={organization}{&count*,max_created_at*,min_created_at*,page_token*}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `outgoing_communications:read`Returns a list of outgoing SMS and email communications.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse?> GetAsOutgoing_communicationsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder.Outgoing_communicationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse> GetAsOutgoing_communicationsGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder.Outgoing_communicationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications400Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `outgoing_communications:read`Returns a list of outgoing SMS and email communications.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsOutgoing_communicationsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder.Outgoing_communicationsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder.Outgoing_communicationsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications400Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.Outgoing_communications500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `outgoing_communications:read`Returns a list of outgoing SMS and email communications.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder.Outgoing_communicationsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder.Outgoing_communicationsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `outgoing_communications:read`Returns a list of outgoing SMS and email communications.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Outgoing_communicationsRequestBuilderGetQueryParameters 
        {
            /// <summary>The number of records to return</summary>
            [QueryParameter("count")]
            public int? Count { get; set; }
            /// <summary>Include outgoing communications that were created prior to this time (sample time format: &quot;2020-01-02T03:04:05.678Z&quot;). This time should use the UTC timezone</summary>
            [QueryParameter("max_created_at")]
            public DateTimeOffset? MaxCreatedAt { get; set; }
            /// <summary>Include outgoing communications that were created after this time (sample time format: &quot;2020-01-02T03:04:05.678Z&quot;). This time should use the UTC timezone</summary>
            [QueryParameter("min_created_at")]
            public DateTimeOffset? MinCreatedAt { get; set; }
            /// <summary>Return outgoing communications from the organization associated with this URI</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("organization")]
            public string? Organization { get; set; }
#nullable restore
#else
            [QueryParameter("organization")]
            public string Organization { get; set; }
#endif
            /// <summary>The token to pass to get the next portion of the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page_token")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("page_token")]
            public string PageToken { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Outgoing_communicationsRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Outgoing_communications.Outgoing_communicationsRequestBuilder.Outgoing_communicationsRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
