// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Calendly.OpenApiClient.User_busy_times
{
    /// <summary>
    /// Builds and executes requests for operations under \user_busy_times
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class User_busy_timesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public User_busy_timesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user_busy_times?end_time={end_time}&start_time={start_time}&user={user}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public User_busy_timesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/user_busy_times?end_time={end_time}&start_time={start_time}&user={user}", rawUrl)
        {
        }
        /// <summary>
        /// Returns an ascending list of user internal and external scheduled events within a specified date range.Date range can be no greater than 1 week (7 days).**NOTE:*** This endpoint does not support traditional keyset pagination.* External events will only be returned for calendars that have &quot;Check for conflicts&quot; configured.&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `availability:read`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_times424Error">When receiving a 424 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesGetResponse?> GetAsUser_busy_timesGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder.User_busy_timesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesGetResponse> GetAsUser_busy_timesGetResponseAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder.User_busy_timesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times401Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times404Error.CreateFromDiscriminatorValue },
                { "424", global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_times424Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesGetResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns an ascending list of user internal and external scheduled events within a specified date range.Date range can be no greater than 1 week (7 days).**NOTE:*** This endpoint does not support traditional keyset pagination.* External events will only be returned for calendars that have &quot;Check for conflicts&quot; configured.&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `availability:read`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_times424Error">When receiving a 424 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use GetAsUser_busy_timesGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder.User_busy_timesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder.User_busy_timesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times401Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times404Error.CreateFromDiscriminatorValue },
                { "424", global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_times424Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.User_busy_times500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns an ascending list of user internal and external scheduled events within a specified date range.Date range can be no greater than 1 week (7 days).**NOTE:*** This endpoint does not support traditional keyset pagination.* External events will only be returned for calendars that have &quot;Check for conflicts&quot; configured.&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `availability:read`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder.User_busy_timesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder.User_busy_timesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns an ascending list of user internal and external scheduled events within a specified date range.Date range can be no greater than 1 week (7 days).**NOTE:*** This endpoint does not support traditional keyset pagination.* External events will only be returned for calendars that have &quot;Check for conflicts&quot; configured.&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `availability:read`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class User_busy_timesRequestBuilderGetQueryParameters 
        {
            /// <summary>End time of the requested availability range. Date must be in the future of start_time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end_time")]
            public string? EndTime { get; set; }
#nullable restore
#else
            [QueryParameter("end_time")]
            public string EndTime { get; set; }
#endif
            /// <summary>Start time of the requested availability range. Date cannot be in the past.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start_time")]
            public string? StartTime { get; set; }
#nullable restore
#else
            [QueryParameter("start_time")]
            public string StartTime { get; set; }
#endif
            /// <summary>The uri associated with the user</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("user")]
            public string? User { get; set; }
#nullable restore
#else
            [QueryParameter("user")]
            public string User { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class User_busy_timesRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.User_busy_times.User_busy_timesRequestBuilder.User_busy_timesRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
