// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events
{
    /// <summary>
    /// Builds and executes requests for operations under \data_compliance\deletion\events
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data_compliance/deletion/events", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data_compliance/deletion/events", rawUrl)
        {
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `data_compliance:write`To submit a request to remove scheduled events data within a time range for your organization, use this endpoint. Requests for data deletion can take up to 7 days to complete.Time range can be no greater than 24 months and must occur in the past.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostResponse?> PostAsEventsPostResponseAsync(global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostResponse> PostAsEventsPostResponseAsync(global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.Events400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Calendly.OpenApiClient.Models.Events401Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.Events404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.Events500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `data_compliance:write`To submit a request to remove scheduled events data within a time range for your organization, use this endpoint. Requests for data deletion can take up to 7 days to complete.Time range can be no greater than 24 months and must occur in the past.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Events500Error">When receiving a 500 status code</exception>
        [Obsolete("This method is obsolete. Use PostAsEventsPostResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsResponse?> PostAsync(global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsResponse> PostAsync(global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.Events400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Calendly.OpenApiClient.Models.Events401Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.Events404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.Events500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `data_compliance:write`To submit a request to remove scheduled events data within a time range for your organization, use this endpoint. Requests for data deletion can take up to 7 days to complete.Time range can be no greater than 24 months and must occur in the past.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Calendly.OpenApiClient.Data_compliance.Deletion.Events.EventsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
