// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Polls.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Calendly.OpenApiClient.Polls
{
    /// <summary>
    /// Builds and executes requests for operations under \polls
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PollsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Calendly.OpenApiClient.polls.item collection</summary>
        /// <param name="position">The poll&apos;s unique identifier</param>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Polls.Item.WithUuItemRequestBuilder"/></returns>
        public global::Soenneker.Calendly.OpenApiClient.Polls.Item.WithUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("uuid", position);
                return new global::Soenneker.Calendly.OpenApiClient.Polls.Item.WithUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Polls.PollsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PollsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/polls", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Polls.PollsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PollsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/polls", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
