// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.One_off_event_types
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum One_off_event_typesPostRequestBody_locationMember3_kind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "gotomeeting_conference")]
        #pragma warning disable CS1591
        Gotomeeting_conference,
        #pragma warning restore CS1591
    }
}
