// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Calendly.OpenApiClient.One_off_event_types
{
    /// <summary>
    /// Builds and executes requests for operations under \one_off_event_types
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class One_off_event_typesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public One_off_event_typesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/one_off_event_types", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public One_off_event_typesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/one_off_event_types", rawUrl)
        {
        }
        /// <summary>
        /// Creates One-Off Event Type&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `event_types:write`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostResponse?> PostAsync(global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostResponse> PostAsync(global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types401Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.One_off_event_types500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Creates One-Off Event Type&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `event_types:write`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Calendly.OpenApiClient.One_off_event_types.One_off_event_typesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
