// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Shares
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SharesPostRequestBody_availability_rule_rules_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "wday")]
        #pragma warning disable CS1591
        Wday,
        #pragma warning restore CS1591
        [EnumMember(Value = "date")]
        #pragma warning disable CS1591
        Date,
        #pragma warning restore CS1591
    }
}
