// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Shares
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SharesPostRequestBody_period_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "available_moving")]
        #pragma warning disable CS1591
        Available_moving,
        #pragma warning restore CS1591
        [EnumMember(Value = "moving")]
        #pragma warning disable CS1591
        Moving,
        #pragma warning restore CS1591
        [EnumMember(Value = "fixed")]
        #pragma warning disable CS1591
        Fixed,
        #pragma warning restore CS1591
        [EnumMember(Value = "unlimited")]
        #pragma warning disable CS1591
        Unlimited,
        #pragma warning restore CS1591
    }
}
