// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Event_type_availability_schedules
{
    [Obsolete("This class is obsolete. Use Event_type_availability_schedulesGetResponse instead.")]
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Event_type_availability_schedulesResponse : global::Soenneker.Calendly.OpenApiClient.Event_type_availability_schedules.Event_type_availability_schedulesGetResponse, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Event_type_availability_schedules.Event_type_availability_schedulesResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static new global::Soenneker.Calendly.OpenApiClient.Event_type_availability_schedules.Event_type_availability_schedulesResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Event_type_availability_schedules.Event_type_availability_schedulesResponse();
        }
    }
}
#pragma warning restore CS0618
