// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Event_types
{
    /// <summary>The locale on the event type, used to determine the language of the event type&apos;s scheduling page</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Event_typesPostRequestBody_locale
    {
        [EnumMember(Value = "de")]
        #pragma warning disable CS1591
        De,
        #pragma warning restore CS1591
        [EnumMember(Value = "en")]
        #pragma warning disable CS1591
        En,
        #pragma warning restore CS1591
        [EnumMember(Value = "es")]
        #pragma warning disable CS1591
        Es,
        #pragma warning restore CS1591
        [EnumMember(Value = "fr")]
        #pragma warning disable CS1591
        Fr,
        #pragma warning restore CS1591
        [EnumMember(Value = "it")]
        #pragma warning disable CS1591
        It,
        #pragma warning restore CS1591
        [EnumMember(Value = "nl")]
        #pragma warning disable CS1591
        Nl,
        #pragma warning restore CS1591
        [EnumMember(Value = "pt")]
        #pragma warning disable CS1591
        Pt,
        #pragma warning restore CS1591
        [EnumMember(Value = "uk")]
        #pragma warning disable CS1591
        Uk,
        #pragma warning restore CS1591
    }
}
