// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AdhocInboundCallKind
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "inbound_call")]
        #pragma warning disable CS1591
        InboundCall,
        #pragma warning restore CS1591
    }
}
