// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The type of Calendly event (scheduled or reserved) this external event relates to</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CalendarEventKind
    {
        [EnumMember(Value = "scheduled_event")]
        #pragma warning disable CS1591
        ScheduledEvent,
        #pragma warning restore CS1591
        [EnumMember(Value = "reserved_event")]
        #pragma warning disable CS1591
        ReservedEvent,
        #pragma warning restore CS1591
    }
}
