// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// Provides data pertaining to the cancellation of the Event or the Invitee
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Cancellation : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Name of the person whom canceled</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CanceledBy { get; set; }
#nullable restore
#else
        public string CanceledBy { get; set; }
#endif
        /// <summary>The canceler_type property</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.Cancellation_canceler_type? CancelerType { get; set; }
        /// <summary>The moment when the cancellation was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Reason that the cancellation occurred</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Models.Cancellation"/> and sets the default values.
        /// </summary>
        public Cancellation()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.Cancellation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.Cancellation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Models.Cancellation();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "canceled_by", n => { CanceledBy = n.GetStringValue(); } },
                { "canceler_type", n => { CancelerType = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Cancellation_canceler_type>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("canceled_by", CanceledBy);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Cancellation_canceler_type>("canceler_type", CancelerType);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("reason", Reason);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
