// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Cancellation_canceler_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "host")]
        #pragma warning disable CS1591
        Host,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitee")]
        #pragma warning disable CS1591
        Invitee,
        #pragma warning restore CS1591
    }
}
