// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSettingMember1"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.DateRange"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.DaysInFuture"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateOneOffEventTypeRequestDateSetting : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSettingMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSettingMember1? CreateOneOffEventTypeRequestDateSettingMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSettingMember1 CreateOneOffEventTypeRequestDateSettingMember1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.DateRange"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.DateRange? DateRange { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.DateRange DateRange { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.DaysInFuture"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.DaysInFuture? DaysInFuture { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.DaysInFuture DaysInFuture { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSetting"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSetting CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSetting();
            if("DateRange".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DateRange = new global::Soenneker.Calendly.OpenApiClient.Models.DateRange();
            }
            else if("DaysInFuture".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.DaysInFuture = new global::Soenneker.Calendly.OpenApiClient.Models.DaysInFuture();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CreateOneOffEventTypeRequestDateSettingMember1 != null)
            {
                return CreateOneOffEventTypeRequestDateSettingMember1.GetFieldDeserializers();
            }
            else if(DateRange != null)
            {
                return DateRange.GetFieldDeserializers();
            }
            else if(DaysInFuture != null)
            {
                return DaysInFuture.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(CreateOneOffEventTypeRequestDateSettingMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestDateSettingMember1>(null, CreateOneOffEventTypeRequestDateSettingMember1);
            }
            else if(DateRange != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.DateRange>(null, DateRange);
            }
            else if(DaysInFuture != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.DaysInFuture>(null, DaysInFuture);
            }
        }
    }
}
#pragma warning restore CS0618
