// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CreateOneOffEventType_date_settingMember2_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "days_in_future")]
        #pragma warning disable CS1591
        Days_in_future,
        #pragma warning restore CS1591
    }
}
