// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocCustomLocation"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocGoogleConference"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocGotoMeetingConference"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocInboundCall"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocInPersonMeeting"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocInviteeSpecifiedLocation"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocMicrosoftTeamsConference"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocOutboundCall"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocWebExConference"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocZoomConference"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateOneOffEventTypeRequestLocation : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocCustomLocation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocCustomLocation? AdhocCustomLocation { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocCustomLocation AdhocCustomLocation { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocGoogleConference"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocGoogleConference? AdhocGoogleConference { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocGoogleConference AdhocGoogleConference { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocGotoMeetingConference"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocGotoMeetingConference? AdhocGotoMeetingConference { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocGotoMeetingConference AdhocGotoMeetingConference { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocInboundCall"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocInboundCall? AdhocInboundCall { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocInboundCall AdhocInboundCall { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocInPersonMeeting"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocInPersonMeeting? AdhocInPersonMeeting { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocInPersonMeeting AdhocInPersonMeeting { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocInviteeSpecifiedLocation"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocInviteeSpecifiedLocation? AdhocInviteeSpecifiedLocation { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocInviteeSpecifiedLocation AdhocInviteeSpecifiedLocation { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocMicrosoftTeamsConference"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocMicrosoftTeamsConference? AdhocMicrosoftTeamsConference { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocMicrosoftTeamsConference AdhocMicrosoftTeamsConference { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocOutboundCall"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocOutboundCall? AdhocOutboundCall { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocOutboundCall AdhocOutboundCall { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocWebExConference"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocWebExConference? AdhocWebExConference { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocWebExConference AdhocWebExConference { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.AdhocZoomConference"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocZoomConference? AdhocZoomConference { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.AdhocZoomConference AdhocZoomConference { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestLocation"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestLocation CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Calendly.OpenApiClient.Models.CreateOneOffEventTypeRequestLocation();
            if("AdhocCustomLocation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocCustomLocation = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocCustomLocation();
            }
            else if("AdhocGoogleConference".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocGoogleConference = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocGoogleConference();
            }
            else if("AdhocGotoMeetingConference".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocGotoMeetingConference = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocGotoMeetingConference();
            }
            else if("AdhocInPersonMeeting".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocInPersonMeeting = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocInPersonMeeting();
            }
            else if("AdhocInboundCall".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocInboundCall = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocInboundCall();
            }
            else if("AdhocInviteeSpecifiedLocation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocInviteeSpecifiedLocation = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocInviteeSpecifiedLocation();
            }
            else if("AdhocMicrosoftTeamsConference".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocMicrosoftTeamsConference = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocMicrosoftTeamsConference();
            }
            else if("AdhocOutboundCall".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocOutboundCall = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocOutboundCall();
            }
            else if("AdhocWebExConference".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocWebExConference = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocWebExConference();
            }
            else if("AdhocZoomConference".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.AdhocZoomConference = new global::Soenneker.Calendly.OpenApiClient.Models.AdhocZoomConference();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(AdhocCustomLocation != null)
            {
                return AdhocCustomLocation.GetFieldDeserializers();
            }
            else if(AdhocGoogleConference != null)
            {
                return AdhocGoogleConference.GetFieldDeserializers();
            }
            else if(AdhocGotoMeetingConference != null)
            {
                return AdhocGotoMeetingConference.GetFieldDeserializers();
            }
            else if(AdhocInboundCall != null)
            {
                return AdhocInboundCall.GetFieldDeserializers();
            }
            else if(AdhocInPersonMeeting != null)
            {
                return AdhocInPersonMeeting.GetFieldDeserializers();
            }
            else if(AdhocInviteeSpecifiedLocation != null)
            {
                return AdhocInviteeSpecifiedLocation.GetFieldDeserializers();
            }
            else if(AdhocMicrosoftTeamsConference != null)
            {
                return AdhocMicrosoftTeamsConference.GetFieldDeserializers();
            }
            else if(AdhocOutboundCall != null)
            {
                return AdhocOutboundCall.GetFieldDeserializers();
            }
            else if(AdhocWebExConference != null)
            {
                return AdhocWebExConference.GetFieldDeserializers();
            }
            else if(AdhocZoomConference != null)
            {
                return AdhocZoomConference.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(AdhocCustomLocation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocCustomLocation>(null, AdhocCustomLocation);
            }
            else if(AdhocGoogleConference != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocGoogleConference>(null, AdhocGoogleConference);
            }
            else if(AdhocGotoMeetingConference != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocGotoMeetingConference>(null, AdhocGotoMeetingConference);
            }
            else if(AdhocInboundCall != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocInboundCall>(null, AdhocInboundCall);
            }
            else if(AdhocInPersonMeeting != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocInPersonMeeting>(null, AdhocInPersonMeeting);
            }
            else if(AdhocInviteeSpecifiedLocation != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocInviteeSpecifiedLocation>(null, AdhocInviteeSpecifiedLocation);
            }
            else if(AdhocMicrosoftTeamsConference != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocMicrosoftTeamsConference>(null, AdhocMicrosoftTeamsConference);
            }
            else if(AdhocOutboundCall != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocOutboundCall>(null, AdhocOutboundCall);
            }
            else if(AdhocWebExConference != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocWebExConference>(null, AdhocWebExConference);
            }
            else if(AdhocZoomConference != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.AdhocZoomConference>(null, AdhocZoomConference);
            }
        }
    }
}
#pragma warning restore CS0618
