// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DateRangeType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "date_range")]
        #pragma warning disable CS1591
        DateRange,
        #pragma warning restore CS1591
    }
}
