// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Indicates that the event host (publisher) will call the invitee</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Event_locationMember2_type
    {
        [EnumMember(Value = "outbound_call")]
        #pragma warning disable CS1591
        Outbound_call,
        #pragma warning restore CS1591
    }
}
