// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The type of response that the invitee provides to the custom question; can be one or multiple lines of text, a phone number, or single- or multiple-select.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventTypePayload_custom_questions_type
    {
        [EnumMember(Value = "string")]
        #pragma warning disable CS1591
        String,
        #pragma warning restore CS1591
        [EnumMember(Value = "text")]
        #pragma warning disable CS1591
        Text,
        #pragma warning restore CS1591
        [EnumMember(Value = "phone_number")]
        #pragma warning disable CS1591
        Phone_number,
        #pragma warning restore CS1591
        [EnumMember(Value = "single_select")]
        #pragma warning disable CS1591
        Single_select,
        #pragma warning restore CS1591
        [EnumMember(Value = "multi_select")]
        #pragma warning disable CS1591
        Multi_select,
        #pragma warning restore CS1591
    }
}
