// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The event location is a Google Meet or Hangouts conference</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Event_locationMember4_type
    {
        [EnumMember(Value = "google_conference")]
        #pragma warning disable CS1591
        Google_conference,
        #pragma warning restore CS1591
    }
}
