// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EventTypeInviteeQuestionType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "event_type_invitee_question")]
        #pragma warning disable CS1591
        EventTypeInviteeQuestion,
        #pragma warning restore CS1591
    }
}
