// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Indicates if the event type is &quot;AdhocEventType&quot; (ad hoc event) or &quot;StandardEventType&quot; (standard event type)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventTypePayload_type
    {
        [EnumMember(Value = "StandardEventType")]
        #pragma warning disable CS1591
        StandardEventType,
        #pragma warning restore CS1591
        [EnumMember(Value = "AdhocEventType")]
        #pragma warning disable CS1591
        AdhocEventType,
        #pragma warning restore CS1591
    }
}
