// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Indicates if the event type is &quot;solo&quot; (belongs to an individual user) or &quot;group&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EventTypePayload_kind
    {
        [EnumMember(Value = "solo")]
        #pragma warning disable CS1591
        Solo,
        #pragma warning restore CS1591
        [EnumMember(Value = "group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
    }
}
