// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// A configuration for an Event Type
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventType : IAdditionalDataHolder, IParsable
    {
        /// <summary>Indicates if the event is active or not.</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Indicates if this event type is managed by an organization admin</summary>
        public bool? AdminManaged { get; set; }
        /// <summary>Indicates if the event type is for a poll or an instant booking</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.EventType_booking_method? BookingMethod { get; set; }
        /// <summary>The hexadecimal color value of the event type&apos;s scheduling page</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>The moment the event type was created (e.g. &quot;2020-01-02T03:04:05.678123Z&quot;)</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The custom_questions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Calendly.OpenApiClient.Models.EventType_custom_questions>? CustomQuestions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Calendly.OpenApiClient.Models.EventType_custom_questions> CustomQuestions { get; set; }
#endif
        /// <summary>The moment the event type was deleted (e.g. &quot;2020-01-02T03:04:05.678123Z&quot;). Since event types can be deleted but their scheduled events remain it&apos;s useful to fetch a deleted event type when you still require event type data for a scheduled event.</summary>
        public DateTimeOffset? DeletedAt { get; set; }
        /// <summary>The event type&apos;s description (formatted with HTML)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescriptionHtml { get; set; }
#nullable restore
#else
        public string DescriptionHtml { get; set; }
#endif
        /// <summary>The event type&apos;s description (in non formatted text)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DescriptionPlain { get; set; }
#nullable restore
#else
        public string DescriptionPlain { get; set; }
#endif
        /// <summary>The length of sessions booked with this event type</summary>
        public double? Duration { get; set; }
        /// <summary>Array of duration options. Always null for adhoc event types.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? DurationOptions { get; set; }
#nullable restore
#else
        public List<int?> DurationOptions { get; set; }
#endif
        /// <summary>Contents of a note that may be associated with the event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InternalNote { get; set; }
#nullable restore
#else
        public string InternalNote { get; set; }
#endif
        /// <summary>The is_paid property</summary>
        public bool? IsPaid { get; set; }
        /// <summary>Indicates if the event type is &quot;solo&quot; (belongs to an individual user) or &quot;group&quot;</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.EventType_kind? Kind { get; set; }
        /// <summary>The locale on the event type, used to determine the language of the event type&apos;s scheduling page</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.EventType_locale? Locale { get; set; }
        /// <summary>Configuration information for each possible location for this Event Type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Calendly.OpenApiClient.Models.LocationConfiguration>? Locations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Calendly.OpenApiClient.Models.LocationConfiguration> Locations { get; set; }
#endif
        /// <summary>The event type name (in human-readable format)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Indicates if the event type is &quot;round robin&quot; (alternates between hosts) or &quot;collective&quot; (invitees pick a time when all participants are available) or “multi-pool” (considers availability delineated by pools of participants) or &quot;null&quot; (the event type doesn’t consider the availability of a group participants)</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.EventType_pooling_type? PoolingType { get; set; }
        /// <summary>Position order of Event Type, starting with 0 (for display purposes)</summary>
        public int? Position { get; set; }
        /// <summary>The publicly visible profile of a User or a Team that&apos;s associated with the Event Type (note: some Event Types don&apos;t have profiles)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.Profile? Profile { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.Profile Profile { get; set; }
#endif
        /// <summary>The URL of the user’s scheduling site where invitees book this event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SchedulingUrl { get; set; }
#nullable restore
#else
        public string SchedulingUrl { get; set; }
#endif
        /// <summary>Indicates if the event type is hidden on the owner&apos;s main scheduling page</summary>
        public bool? Secret { get; set; }
        /// <summary>The portion of the event type&apos;s URL that identifies a specific web page (in a human-readable format)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>Indicates if the event type is &quot;AdhocEventType&quot; (ad hoc event) or &quot;StandardEventType&quot; (standard event type)</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.EventType_type? Type { get; set; }
        /// <summary>The moment the event type was last updated (e.g. &quot;2020-01-02T03:04:05.678123Z&quot;)</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Canonical reference (unique identifier) for the event type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Models.EventType"/> and sets the default values.
        /// </summary>
        public EventType()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.EventType"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.EventType CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Models.EventType();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "admin_managed", n => { AdminManaged = n.GetBoolValue(); } },
                { "booking_method", n => { BookingMethod = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_booking_method>(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "custom_questions", n => { CustomQuestions = n.GetCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Models.EventType_custom_questions>(global::Soenneker.Calendly.OpenApiClient.Models.EventType_custom_questions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "deleted_at", n => { DeletedAt = n.GetDateTimeOffsetValue(); } },
                { "description_html", n => { DescriptionHtml = n.GetStringValue(); } },
                { "description_plain", n => { DescriptionPlain = n.GetStringValue(); } },
                { "duration", n => { Duration = n.GetDoubleValue(); } },
                { "duration_options", n => { DurationOptions = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "internal_note", n => { InternalNote = n.GetStringValue(); } },
                { "is_paid", n => { IsPaid = n.GetBoolValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_kind>(); } },
                { "locale", n => { Locale = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_locale>(); } },
                { "locations", n => { Locations = n.GetCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Models.LocationConfiguration>(global::Soenneker.Calendly.OpenApiClient.Models.LocationConfiguration.CreateFromDiscriminatorValue)?.AsList(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "pooling_type", n => { PoolingType = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_pooling_type>(); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "profile", n => { Profile = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.Profile>(global::Soenneker.Calendly.OpenApiClient.Models.Profile.CreateFromDiscriminatorValue); } },
                { "scheduling_url", n => { SchedulingUrl = n.GetStringValue(); } },
                { "secret", n => { Secret = n.GetBoolValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_type>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteBoolValue("admin_managed", AdminManaged);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_booking_method>("booking_method", BookingMethod);
            writer.WriteStringValue("color", Color);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Models.EventType_custom_questions>("custom_questions", CustomQuestions);
            writer.WriteDateTimeOffsetValue("deleted_at", DeletedAt);
            writer.WriteStringValue("description_html", DescriptionHtml);
            writer.WriteStringValue("description_plain", DescriptionPlain);
            writer.WriteDoubleValue("duration", Duration);
            writer.WriteCollectionOfPrimitiveValues<int?>("duration_options", DurationOptions);
            writer.WriteStringValue("internal_note", InternalNote);
            writer.WriteBoolValue("is_paid", IsPaid);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_kind>("kind", Kind);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_locale>("locale", Locale);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Models.LocationConfiguration>("locations", Locations);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_pooling_type>("pooling_type", PoolingType);
            writer.WriteIntValue("position", Position);
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.Profile>("profile", Profile);
            writer.WriteStringValue("scheduling_url", SchedulingUrl);
            writer.WriteBoolValue("secret", Secret);
            writer.WriteStringValue("slug", Slug);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventType_type>("type", Type);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("uri", Uri);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
