// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum Event_type_available_times403Error_title
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Insufficient scope")]
        #pragma warning disable CS1591
        InsufficientScope,
        #pragma warning restore CS1591
    }
}
