// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EventTypePayload_custom_questions : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The invitee’s option(s) for single_select or multi_select type of responses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? AnswerChoices { get; set; }
#nullable restore
#else
        public List<string> AnswerChoices { get; set; }
#endif
        /// <summary>true if the question created by the host is turned ON and visible on the event booking page; false if turned OFF and invisible on the event booking page.</summary>
        public bool? Enabled { get; set; }
        /// <summary>true if the custom question lets invitees record a written response in addition to single-select or multiple-select type of responses; false if it doesn’t.</summary>
        public bool? IncludeOther { get; set; }
        /// <summary>The custom question that the host created for the event type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The numerical position of the question on the event booking page after the name and email address fields.</summary>
        public int? Position { get; set; }
        /// <summary>true if a response to the question created by the host is required for invitees to book the event type; false if not required.</summary>
        public bool? Required { get; set; }
        /// <summary>The type of response that the invitee provides to the custom question; can be one or multiple lines of text, a phone number, or single- or multiple-select.</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload_custom_questions_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload_custom_questions"/> and sets the default values.
        /// </summary>
        public EventTypePayload_custom_questions()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload_custom_questions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload_custom_questions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload_custom_questions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "answer_choices", n => { AnswerChoices = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "include_other", n => { IncludeOther = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "position", n => { Position = n.GetIntValue(); } },
                { "required", n => { Required = n.GetBoolValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload_custom_questions_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("answer_choices", AnswerChoices);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteBoolValue("include_other", IncludeOther);
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("position", Position);
            writer.WriteBoolValue("required", Required);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload_custom_questions_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
