// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Payment provider</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InviteePayload_payment_provider
    {
        [EnumMember(Value = "stripe")]
        #pragma warning disable CS1591
        Stripe,
        #pragma warning restore CS1591
        [EnumMember(Value = "paypal")]
        #pragma warning disable CS1591
        Paypal,
        #pragma warning restore CS1591
    }
}
