// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The method used to schedule the event</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InviteePayload_scheduling_method
    {
        [EnumMember(Value = "instant_book")]
        #pragma warning disable CS1591
        Instant_book,
        #pragma warning restore CS1591
    }
}
