// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The event location is a GoToMeeting conference</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InviteeGotoMeetingConferenceKind
    {
        [EnumMember(Value = "gotomeeting_conference")]
        #pragma warning disable CS1591
        GotomeetingConference,
        #pragma warning restore CS1591
    }
}
