// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Indicates that the event will be an in-person meeting.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InviteePayload_scheduled_event_locationMember1_type
    {
        [EnumMember(Value = "physical")]
        #pragma warning disable CS1591
        Physical,
        #pragma warning restore CS1591
    }
}
