// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Indicates that the invitee will call the event host</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InviteeInboundCallKind
    {
        [EnumMember(Value = "inbound_call")]
        #pragma warning disable CS1591
        InboundCall,
        #pragma warning restore CS1591
    }
}
