// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The method used to schedule the event</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Invitee_scheduling_method
    {
        [EnumMember(Value = "instant_book")]
        #pragma warning disable CS1591
        Instant_book,
        #pragma warning restore CS1591
        [EnumMember(Value = "openapi-json-null-sentinel-value-2BF93600-0FE4-4250-987A-E5DDB203E464")]
        #pragma warning disable CS1591
        OpenapiJsonNullSentinelValue2BF936000FE44250987AE5DDB203E464,
        #pragma warning restore CS1591
    }
}
