// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// Meeting will take place in a Zoom conference. Location details will not be available 6 months after event has occurred.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InviteePayload_scheduled_event_locationMember5 : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The conference metadata supplied by Zoom</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_data? Data { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_data Data { get; set; }
#endif
        /// <summary>Zoom meeting url</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? JoinUrl { get; set; }
#nullable restore
#else
        public string JoinUrl { get; set; }
#endif
        /// <summary>Indicates the current status of the Zoom conference&lt;br/&gt;&amp;nbsp; * Expect only `pushed` status to have non-`null` values for `join_url` &amp; `data` fields.&lt;br/&gt;&amp;nbsp; - `processing` Location details generation pending&lt;br/&gt;&amp;nbsp; - `initiated` Requesting location details from Zoom&lt;br/&gt;&amp;nbsp; - `pushed` Location details are available&lt;br/&gt;&amp;nbsp; - `failed` Error occurred or event has been canceled&lt;br/&gt;&amp;nbsp; - `null` Location details are no longer available</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_status? Status { get; set; }
        /// <summary>The event location is a Zoom conference</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_type? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5"/> and sets the default values.
        /// </summary>
        public InviteePayload_scheduled_event_locationMember5()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_data>(global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_data.CreateFromDiscriminatorValue); } },
                { "join_url", n => { JoinUrl = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_status>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_data>("data", Data);
            writer.WriteStringValue("join_url", JoinUrl);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_status>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload_scheduled_event_locationMember5_type>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
