// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// A meeting recap list item generated for a Calendly scheduled event or an external event.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeetingRecapListItem : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Meeting attendees derived from tracked-meeting participants. Same shape as meeting_recap webhook attendees.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItemAttendeesItem>? Attendees { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItemAttendeesItem> Attendees { get; set; }
#endif
        /// <summary>When the tracked meeting record was created (UTC, ISO 8601).</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Scheduled end time of the meeting (UTC, ISO 8601).</summary>
        public DateTimeOffset? EndTime { get; set; }
        /// <summary>URI of the event scheduled via Calendly which this recap belongs to, or null if the recap is for an external event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Event { get; set; }
#nullable restore
#else
        public string Event { get; set; }
#endif
        /// <summary>The polymorphic base type for an event location that Calendly supports</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.Location? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.Location Location { get; set; }
#endif
        /// <summary>Name of the meeting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Scheduled start time of the meeting (UTC, ISO 8601).</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>Processing state of the recap.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Canonical reference (unique identifier) for the transcript. Always present onlist items; the transcript resource itself may still be unavailable until therecap is Available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Transcript { get; set; }
#nullable restore
#else
        public string Transcript { get; set; }
#endif
        /// <summary>When the tracked meeting record was last updated (UTC, ISO 8601).</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Canonical reference (unique identifier) for the recap.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItem"/> and sets the default values.
        /// </summary>
        public MeetingRecapListItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attendees", n => { Attendees = n.GetCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItemAttendeesItem>(global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItemAttendeesItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "end_time", n => { EndTime = n.GetDateTimeOffsetValue(); } },
                { "event", n => { Event = n.GetStringValue(); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.Location>(global::Soenneker.Calendly.OpenApiClient.Models.Location.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "start_time", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "transcript", n => { Transcript = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapListItemAttendeesItem>("attendees", Attendees);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("end_time", EndTime);
            writer.WriteStringValue("event", Event);
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.Location>("location", Location);
            writer.WriteStringValue("name", Name);
            writer.WriteDateTimeOffsetValue("start_time", StartTime);
            writer.WriteStringValue("status", Status);
            writer.WriteStringValue("transcript", Transcript);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("uri", Uri);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
