// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// V2 webhook payload for `meeting_recap.updated`
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MeetingRecapUpdatedWebhookPayload : IParsable
    {
        /// <summary>Snapshot of the related scheduled event</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadEvent? Event { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadEvent Event { get; set; }
#endif
        /// <summary>Updated meeting recap resource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadRecap? Recap { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadRecap Recap { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "event", n => { Event = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadEvent>(global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadEvent.CreateFromDiscriminatorValue); } },
                { "recap", n => { Recap = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadRecap>(global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadRecap.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadEvent>("event", Event);
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayloadRecap>("recap", Recap);
        }
    }
}
#pragma warning restore CS0618
