// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The type of location configuration</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MeetingLocationKind
    {
        [EnumMember(Value = "ask_invitee")]
        #pragma warning disable CS1591
        AskInvitee,
        #pragma warning restore CS1591
        [EnumMember(Value = "custom")]
        #pragma warning disable CS1591
        Custom,
        #pragma warning restore CS1591
        [EnumMember(Value = "google_conference")]
        #pragma warning disable CS1591
        GoogleConference,
        #pragma warning restore CS1591
        [EnumMember(Value = "gotomeeting_conference")]
        #pragma warning disable CS1591
        GotomeetingConference,
        #pragma warning restore CS1591
        [EnumMember(Value = "inbound_call")]
        #pragma warning disable CS1591
        InboundCall,
        #pragma warning restore CS1591
        [EnumMember(Value = "microsoft_teams_conference")]
        #pragma warning disable CS1591
        MicrosoftTeamsConference,
        #pragma warning restore CS1591
        [EnumMember(Value = "outbound_call")]
        #pragma warning disable CS1591
        OutboundCall,
        #pragma warning restore CS1591
        [EnumMember(Value = "physical")]
        #pragma warning disable CS1591
        Physical,
        #pragma warning restore CS1591
        [EnumMember(Value = "webex_conference")]
        #pragma warning disable CS1591
        WebexConference,
        #pragma warning restore CS1591
        [EnumMember(Value = "zoom_conference")]
        #pragma warning disable CS1591
        ZoomConference,
        #pragma warning restore CS1591
    }
}
