// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// Organization object
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Organization : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp of when the organization was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Indicates whether the organization is a single-user or multiple-user organization</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.Organization_kind? Kind { get; set; }
        /// <summary>The Organization name (in human-readable format)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Active subscription plan or trial plan</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.Organization_plan? Plan { get; set; }
        /// <summary>Current stage of organization</summary>
        public global::Soenneker.Calendly.OpenApiClient.Models.Organization_stage? Stage { get; set; }
        /// <summary>Timestamp of when the organization was created or updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Canonical resource reference</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Uri { get; set; }
#nullable restore
#else
        public string Uri { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Models.Organization"/> and sets the default values.
        /// </summary>
        public Organization()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.Organization"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.Organization CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Models.Organization();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "kind", n => { Kind = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Organization_kind>(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "plan", n => { Plan = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Organization_plan>(); } },
                { "stage", n => { Stage = n.GetEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Organization_stage>(); } },
                { "updated_at", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "uri", n => { Uri = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Organization_kind>("kind", Kind);
            writer.WriteStringValue("name", Name);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Organization_plan>("plan", Plan);
            writer.WriteEnumValue<global::Soenneker.Calendly.OpenApiClient.Models.Organization_stage>("stage", Stage);
            writer.WriteDateTimeOffsetValue("updated_at", UpdatedAt);
            writer.WriteStringValue("uri", Uri);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
