// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Current stage of organization</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Organization_stage
    {
        [EnumMember(Value = "trial")]
        #pragma warning disable CS1591
        Trial,
        #pragma warning restore CS1591
        [EnumMember(Value = "free")]
        #pragma warning disable CS1591
        Free,
        #pragma warning restore CS1591
        [EnumMember(Value = "paid")]
        #pragma warning disable CS1591
        Paid,
        #pragma warning restore CS1591
    }
}
