// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Indicates that the event location will be selected by the invitee</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PostInvitee_locationMember9_kind
    {
        [EnumMember(Value = "ask_invitee")]
        #pragma warning disable CS1591
        Ask_invitee,
        #pragma warning restore CS1591
    }
}
