// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The preferred time notation of the invitee</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RecentInviteeTimeNotation
    {
        [EnumMember(Value = "12h")]
        #pragma warning disable CS1591
        Value12H,
        #pragma warning restore CS1591
        [EnumMember(Value = "24h")]
        #pragma warning disable CS1591
        Value24H,
        #pragma warning restore CS1591
    }
}
