// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Indicates if the routing form submission resulted in a custom &quot;thank you&quot; message.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubmissionCustomMessageResultType
    {
        [EnumMember(Value = "custom_message")]
        #pragma warning disable CS1591
        CustomMessage,
        #pragma warning restore CS1591
    }
}
