// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum SuperAdminRolePermissionsItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "billing")]
        #pragma warning disable CS1591
        Billing,
        #pragma warning restore CS1591
        [EnumMember(Value = "deals")]
        #pragma warning disable CS1591
        Deals,
        #pragma warning restore CS1591
        [EnumMember(Value = "pretend")]
        #pragma warning disable CS1591
        Pretend,
        #pragma warning restore CS1591
        [EnumMember(Value = "background_jobs")]
        #pragma warning disable CS1591
        BackgroundJobs,
        #pragma warning restore CS1591
        [EnumMember(Value = "rollout")]
        #pragma warning disable CS1591
        Rollout,
        #pragma warning restore CS1591
        [EnumMember(Value = "trial")]
        #pragma warning disable CS1591
        Trial,
        #pragma warning restore CS1591
        [EnumMember(Value = "view_events")]
        #pragma warning disable CS1591
        ViewEvents,
        #pragma warning restore CS1591
        [EnumMember(Value = "spam_blocking")]
        #pragma warning disable CS1591
        SpamBlocking,
        #pragma warning restore CS1591
        [EnumMember(Value = "bulk_actions")]
        #pragma warning disable CS1591
        BulkActions,
        #pragma warning restore CS1591
        [EnumMember(Value = "api_management")]
        #pragma warning disable CS1591
        ApiManagement,
        #pragma warning restore CS1591
        [EnumMember(Value = "super_admin_feedbacks")]
        #pragma warning disable CS1591
        SuperAdminFeedbacks,
        #pragma warning restore CS1591
        [EnumMember(Value = "communication_management")]
        #pragma warning disable CS1591
        CommunicationManagement,
        #pragma warning restore CS1591
        [EnumMember(Value = "account_suspension")]
        #pragma warning disable CS1591
        AccountSuspension,
        #pragma warning restore CS1591
        [EnumMember(Value = "template_migration_rollback")]
        #pragma warning disable CS1591
        TemplateMigrationRollback,
        #pragma warning restore CS1591
    }
}
