// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>By default every host on the Event Type shares an identical schedule.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateEventTypeAvailabilityRequestAvailabilitySetting
    {
        [EnumMember(Value = "host")]
        #pragma warning disable CS1591
        Host,
        #pragma warning restore CS1591
    }
}
