// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>Time notation used by the user. Accepts &quot;12h&quot; or &quot;24h&quot; as a value.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum User_time_notation
    {
        [EnumMember(Value = "12h")]
        #pragma warning disable CS1591
        OneTwoh,
        #pragma warning restore CS1591
        [EnumMember(Value = "24h")]
        #pragma warning disable CS1591
        TwoFourh,
        #pragma warning restore CS1591
    }
}
