// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Calendly.OpenApiClient.Models.ContactCreatedWebhookPayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.ContactDeletedWebhookPayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.ContactUpdatedWebhookPayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapCreatedWebhookPayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapDeletedWebhookPayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Models.RoutingFormSubmission"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WebhookPayloadPayload : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.ContactCreatedWebhookPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.ContactCreatedWebhookPayload? ContactCreatedWebhookPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.ContactCreatedWebhookPayload ContactCreatedWebhookPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.ContactDeletedWebhookPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.ContactDeletedWebhookPayload? ContactDeletedWebhookPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.ContactDeletedWebhookPayload ContactDeletedWebhookPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.ContactUpdatedWebhookPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.ContactUpdatedWebhookPayload? ContactUpdatedWebhookPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.ContactUpdatedWebhookPayload ContactUpdatedWebhookPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload? EventTypePayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload EventTypePayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload? InviteePayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload InviteePayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapCreatedWebhookPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapCreatedWebhookPayload? MeetingRecapCreatedWebhookPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapCreatedWebhookPayload MeetingRecapCreatedWebhookPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapDeletedWebhookPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapDeletedWebhookPayload? MeetingRecapDeletedWebhookPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapDeletedWebhookPayload MeetingRecapDeletedWebhookPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload? MeetingRecapUpdatedWebhookPayload { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload MeetingRecapUpdatedWebhookPayload { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Models.RoutingFormSubmission"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Models.RoutingFormSubmission? RoutingFormSubmission { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Models.RoutingFormSubmission RoutingFormSubmission { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayloadPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayloadPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayloadPayload();
            if("ContactCreatedWebhookPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContactCreatedWebhookPayload = new global::Soenneker.Calendly.OpenApiClient.Models.ContactCreatedWebhookPayload();
            }
            else if("ContactDeletedWebhookPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContactDeletedWebhookPayload = new global::Soenneker.Calendly.OpenApiClient.Models.ContactDeletedWebhookPayload();
            }
            else if("ContactUpdatedWebhookPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ContactUpdatedWebhookPayload = new global::Soenneker.Calendly.OpenApiClient.Models.ContactUpdatedWebhookPayload();
            }
            else if("EventTypePayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EventTypePayload = new global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload();
            }
            else if("InviteePayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InviteePayload = new global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload();
            }
            else if("MeetingRecapCreatedWebhookPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MeetingRecapCreatedWebhookPayload = new global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapCreatedWebhookPayload();
            }
            else if("MeetingRecapDeletedWebhookPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MeetingRecapDeletedWebhookPayload = new global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapDeletedWebhookPayload();
            }
            else if("MeetingRecapUpdatedWebhookPayload".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.MeetingRecapUpdatedWebhookPayload = new global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload();
            }
            else if("RoutingFormSubmission".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.RoutingFormSubmission = new global::Soenneker.Calendly.OpenApiClient.Models.RoutingFormSubmission();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ContactCreatedWebhookPayload != null)
            {
                return ContactCreatedWebhookPayload.GetFieldDeserializers();
            }
            else if(ContactDeletedWebhookPayload != null)
            {
                return ContactDeletedWebhookPayload.GetFieldDeserializers();
            }
            else if(ContactUpdatedWebhookPayload != null)
            {
                return ContactUpdatedWebhookPayload.GetFieldDeserializers();
            }
            else if(EventTypePayload != null)
            {
                return EventTypePayload.GetFieldDeserializers();
            }
            else if(InviteePayload != null)
            {
                return InviteePayload.GetFieldDeserializers();
            }
            else if(MeetingRecapCreatedWebhookPayload != null)
            {
                return MeetingRecapCreatedWebhookPayload.GetFieldDeserializers();
            }
            else if(MeetingRecapDeletedWebhookPayload != null)
            {
                return MeetingRecapDeletedWebhookPayload.GetFieldDeserializers();
            }
            else if(MeetingRecapUpdatedWebhookPayload != null)
            {
                return MeetingRecapUpdatedWebhookPayload.GetFieldDeserializers();
            }
            else if(RoutingFormSubmission != null)
            {
                return RoutingFormSubmission.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ContactCreatedWebhookPayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.ContactCreatedWebhookPayload>(null, ContactCreatedWebhookPayload);
            }
            else if(ContactDeletedWebhookPayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.ContactDeletedWebhookPayload>(null, ContactDeletedWebhookPayload);
            }
            else if(ContactUpdatedWebhookPayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.ContactUpdatedWebhookPayload>(null, ContactUpdatedWebhookPayload);
            }
            else if(EventTypePayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.EventTypePayload>(null, EventTypePayload);
            }
            else if(InviteePayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.InviteePayload>(null, InviteePayload);
            }
            else if(MeetingRecapCreatedWebhookPayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapCreatedWebhookPayload>(null, MeetingRecapCreatedWebhookPayload);
            }
            else if(MeetingRecapDeletedWebhookPayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapDeletedWebhookPayload>(null, MeetingRecapDeletedWebhookPayload);
            }
            else if(MeetingRecapUpdatedWebhookPayload != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.MeetingRecapUpdatedWebhookPayload>(null, MeetingRecapUpdatedWebhookPayload);
            }
            else if(RoutingFormSubmission != null)
            {
                writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Models.RoutingFormSubmission>(null, RoutingFormSubmission);
            }
        }
    }
}
#pragma warning restore CS0618
