// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Models
{
    /// <summary>The scope of the webhook subscription</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum WebhookSubscription_scope
    {
        [EnumMember(Value = "user")]
        #pragma warning disable CS1591
        User,
        #pragma warning restore CS1591
        [EnumMember(Value = "organization")]
        #pragma warning disable CS1591
        Organization,
        #pragma warning restore CS1591
        [EnumMember(Value = "group")]
        #pragma warning disable CS1591
        Group,
        #pragma warning restore CS1591
    }
}
