// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Sample_webhook_data
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetEventQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "invitee.created")]
        #pragma warning disable CS1591
        InviteeCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitee.canceled")]
        #pragma warning disable CS1591
        InviteeCanceled,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitee_no_show.created")]
        #pragma warning disable CS1591
        Invitee_no_showCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "invitee_no_show.deleted")]
        #pragma warning disable CS1591
        Invitee_no_showDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "routing_form_submission.created")]
        #pragma warning disable CS1591
        Routing_form_submissionCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "event_type.created")]
        #pragma warning disable CS1591
        Event_typeCreated,
        #pragma warning restore CS1591
        [EnumMember(Value = "event_type.deleted")]
        #pragma warning disable CS1591
        Event_typeDeleted,
        #pragma warning restore CS1591
        [EnumMember(Value = "event_type.updated")]
        #pragma warning disable CS1591
        Event_typeUpdated,
        #pragma warning restore CS1591
    }
}
