// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Calendly.OpenApiClient.Sample_webhook_data
{
    /// <summary>
    /// Builds and executes requests for operations under \sample_webhook_data
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Sample_webhook_dataRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sample_webhook_dataRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sample_webhook_data?event={event}&organization={organization}&scope={scope}{&group*,user*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Sample_webhook_dataRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/sample_webhook_data?event={event}&organization={organization}&scope={scope}{&group*,user*}", rawUrl)
        {
        }
        /// <summary>
        /// Test your webhook subscription&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `webhooks:read`
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.InsufficientScopeError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload?> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder.Sample_webhook_dataRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder.Sample_webhook_dataRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Calendly.OpenApiClient.Models.InsufficientScopeError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload>(requestInfo, global::Soenneker.Calendly.OpenApiClient.Models.WebhookPayload.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Test your webhook subscription&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `webhooks:read`
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder.Sample_webhook_dataRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder.Sample_webhook_dataRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Test your webhook subscription&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `webhooks:read`
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Sample_webhook_dataRequestBuilderGetQueryParameters 
        {
            [Obsolete("This property is deprecated, use EventAsGetEventQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("event")]
            public string? Event { get; set; }
#nullable restore
#else
            [QueryParameter("event")]
            public string Event { get; set; }
#endif
            [QueryParameter("event")]
            public global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.GetEventQueryParameterType? EventAsGetEventQueryParameterType { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("group")]
            public string? Group { get; set; }
#nullable restore
#else
            [QueryParameter("group")]
            public string Group { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("organization")]
            public string? Organization { get; set; }
#nullable restore
#else
            [QueryParameter("organization")]
            public string Organization { get; set; }
#endif
            [Obsolete("This property is deprecated, use ScopeAsGetScopeQueryParameterType instead")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("scope")]
            public string? Scope { get; set; }
#nullable restore
#else
            [QueryParameter("scope")]
            public string Scope { get; set; }
#endif
            [QueryParameter("scope")]
            public global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.GetScopeQueryParameterType? ScopeAsGetScopeQueryParameterType { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("user")]
            public string? User { get; set; }
#nullable restore
#else
            [QueryParameter("user")]
            public string User { get; set; }
#endif
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Sample_webhook_dataRequestBuilderGetRequestConfiguration : RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Sample_webhook_data.Sample_webhook_dataRequestBuilder.Sample_webhook_dataRequestBuilderGetQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
