// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Calendly.OpenApiClient.Activity_log_entries
{
    /// <summary>
    /// Builds and executes requests for operations under \activity_log_entries
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Activity_log_entriesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Activity_log_entriesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activity_log_entries?organization={organization}{&action,actor,count*,max_occurred_at*,min_occurred_at*,namespace,page_token*,search_term*,sort}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Activity_log_entriesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/activity_log_entries?organization={organization}{&action,actor,count*,max_occurred_at*,min_occurred_at*,namespace,page_token*,search_term*,sort}", rawUrl)
        {
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `activity_log:read`Returns a list of activity log entries
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Activity_log_entries400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Activity_log_entries404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.Activity_log_entries500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesGetResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder.Activity_log_entriesRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesGetResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder.Activity_log_entriesRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.Activity_log_entries400Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.Activity_log_entries404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.Activity_log_entries500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesGetResponse>(requestInfo, global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesGetResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `activity_log:read`Returns a list of activity log entries
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder.Activity_log_entriesRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder.Activity_log_entriesRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.Activity_log_entriesRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &lt;!-- theme: info --&gt;  &gt; This endpoint requires an &lt;strong&gt;Enterprise&lt;/strong&gt; subscription.  &gt;  &gt; #### Required scopes: `activity_log:read`Returns a list of activity log entries
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Activity_log_entriesRequestBuilderGetQueryParameters 
        {
            /// <summary>The action(s) associated with the entries</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("action")]
            public string[]? Action { get; set; }
#nullable restore
#else
            [QueryParameter("action")]
            public string[] Action { get; set; }
#endif
            /// <summary>Return entries from the user(s) associated with the provided URIs</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("actor")]
            public string[]? Actor { get; set; }
#nullable restore
#else
            [QueryParameter("actor")]
            public string[] Actor { get; set; }
#endif
            /// <summary>The number of rows to return</summary>
            [QueryParameter("count")]
            public int? Count { get; set; }
            /// <summary>Include entries that occurred prior to this time (sample time format: &quot;2020-01-02T03:04:05.678Z&quot;). This time should use the UTC timezone.</summary>
            [QueryParameter("max_occurred_at")]
            public DateTimeOffset? MaxOccurredAt { get; set; }
            /// <summary>Include entries that occurred after this time (sample time format: &quot;2020-01-02T03:04:05.678Z&quot;). This time should use the UTC timezone.</summary>
            [QueryParameter("min_occurred_at")]
            public DateTimeOffset? MinOccurredAt { get; set; }
            /// <summary>The categories of the entries</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("namespace")]
            public string[]? Namespace { get; set; }
#nullable restore
#else
            [QueryParameter("namespace")]
            public string[] Namespace { get; set; }
#endif
            /// <summary>Return activity log entries from the organization associated with this URI</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("organization")]
            public string? Organization { get; set; }
#nullable restore
#else
            [QueryParameter("organization")]
            public string Organization { get; set; }
#endif
            /// <summary>The token to pass to get the next portion of the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page_token")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("page_token")]
            public string PageToken { get; set; }
#endif
            /// <summary>Filters entries based on the search term.Supported operators:  - `|` - to allow filtering by one term or another. Example: `this | that`  - `+` - to allow filtering by one term and another. Example: `this + that`  - `&quot;` - to allow filtering by an exact search term. Example: `&quot;email@website.com&quot;`  - `-` - to omit specific terms from results. Example: `Added -User`  - `()` - to allow specifying precedence during a search. Example: `(this + that) OR (person + place)`  - `*` - to allow prefix searching. Example `*@other-website.com`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("search_term")]
            public string? SearchTerm { get; set; }
#nullable restore
#else
            [QueryParameter("search_term")]
            public string SearchTerm { get; set; }
#endif
            /// <summary>Order results by the specified field and direction. List of {field}:{direction} values.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.GetSortQueryParameterType[]? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public global::Soenneker.Calendly.OpenApiClient.Activity_log_entries.GetSortQueryParameterType[] Sort { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
