// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Activity_log_entries
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSortQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "action:asc")]
        #pragma warning disable CS1591
        ActionAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "action:desc")]
        #pragma warning disable CS1591
        ActionDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "actor.display_name:asc")]
        #pragma warning disable CS1591
        ActorDisplay_nameAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "actor.display_name:desc")]
        #pragma warning disable CS1591
        ActorDisplay_nameDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "actor.uri:asc")]
        #pragma warning disable CS1591
        ActorUriAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "actor.uri:desc")]
        #pragma warning disable CS1591
        ActorUriDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "namespace:asc")]
        #pragma warning disable CS1591
        NamespaceAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "namespace:desc")]
        #pragma warning disable CS1591
        NamespaceDesc,
        #pragma warning restore CS1591
        [EnumMember(Value = "occurred_at:asc")]
        #pragma warning disable CS1591
        Occurred_atAsc,
        #pragma warning restore CS1591
        [EnumMember(Value = "occurred_at:desc")]
        #pragma warning disable CS1591
        Occurred_atDesc,
        #pragma warning restore CS1591
    }
}
