// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Invitees
{
    /// <summary>The event location is a Zoom conference</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InviteesPostRequestBody_locationMember4_kind
    {
        [EnumMember(Value = "zoom_conference")]
        #pragma warning disable CS1591
        Zoom_conference,
        #pragma warning restore CS1591
    }
}
