// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Calendly.OpenApiClient.Invitees
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class InviteesPostRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Emails of invitee guests. Max 10.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? EventGuests { get; set; }
#nullable restore
#else
        public List<string> EventGuests { get; set; }
#endif
        /// <summary>Canonical reference (unique identifier) for the event type being scheduled </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventType { get; set; }
#nullable restore
#else
        public string EventType { get; set; }
#endif
        /// <summary>The invitee property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_invitee? Invitee { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_invitee Invitee { get; set; }
#endif
        /// <summary>The polymorphic base type for an event location that Calendly supports.  Note: - Location.kind must be supplied if location is defined.- Location must match location specified on the EventType.- Do not pass the location object for an EventType with a round_robin pooling_type.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location? Location { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location Location { get; set; }
#endif
        /// <summary>The questions_and_answers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_questions_and_answers>? QuestionsAndAnswers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_questions_and_answers> QuestionsAndAnswers { get; set; }
#endif
        /// <summary>The start time in UTC of the scheduled event</summary>
        public DateTimeOffset? StartTime { get; set; }
        /// <summary>The UTM and Salesforce tracking parameters associated with an Invitee</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_tracking? Tracking { get; set; }
#nullable restore
#else
        public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_tracking Tracking { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody"/> and sets the default values.
        /// </summary>
        public InviteesPostRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "event_guests", n => { EventGuests = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "event_type", n => { EventType = n.GetStringValue(); } },
                { "invitee", n => { Invitee = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_invitee>(global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_invitee.CreateFromDiscriminatorValue); } },
                { "location", n => { Location = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location>(global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location.CreateFromDiscriminatorValue); } },
                { "questions_and_answers", n => { QuestionsAndAnswers = n.GetCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_questions_and_answers>(global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_questions_and_answers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "start_time", n => { StartTime = n.GetDateTimeOffsetValue(); } },
                { "tracking", n => { Tracking = n.GetObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_tracking>(global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_tracking.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("event_guests", EventGuests);
            writer.WriteStringValue("event_type", EventType);
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_invitee>("invitee", Invitee);
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location>("location", Location);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_questions_and_answers>("questions_and_answers", QuestionsAndAnswers);
            writer.WriteDateTimeOffsetValue("start_time", StartTime);
            writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_tracking>("tracking", Tracking);
            writer.WriteAdditionalData(AdditionalData);
        }
        /// <summary>
        /// Composed type wrapper for classes <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember1"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember10"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember2"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember3"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember4"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember5"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember6"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember7"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember8"/>, <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember9"/>
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class InviteesPostRequestBody_location : IComposedTypeWrapper, IParsable
        {
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember1? InviteesPostRequestBodyLocationMember1 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember1 InviteesPostRequestBodyLocationMember1 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember10"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember10? InviteesPostRequestBodyLocationMember10 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember10 InviteesPostRequestBodyLocationMember10 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember2? InviteesPostRequestBodyLocationMember2 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember2 InviteesPostRequestBodyLocationMember2 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember3? InviteesPostRequestBodyLocationMember3 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember3 InviteesPostRequestBodyLocationMember3 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember4"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember4? InviteesPostRequestBodyLocationMember4 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember4 InviteesPostRequestBodyLocationMember4 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember5? InviteesPostRequestBodyLocationMember5 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember5 InviteesPostRequestBodyLocationMember5 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember6"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember6? InviteesPostRequestBodyLocationMember6 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember6 InviteesPostRequestBodyLocationMember6 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember7"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember7? InviteesPostRequestBodyLocationMember7 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember7 InviteesPostRequestBodyLocationMember7 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember8"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember8? InviteesPostRequestBodyLocationMember8 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember8 InviteesPostRequestBodyLocationMember8 { get; set; }
#endif
            /// <summary>Composed type representation for type <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember9"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember9? InviteesPostRequestBodyLocationMember9 { get; set; }
#nullable restore
#else
            public global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember9 InviteesPostRequestBodyLocationMember9 { get; set; }
#endif
            /// <summary>
            /// Creates a new instance of the appropriate class based on discriminator value
            /// </summary>
            /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location"/></returns>
            /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
            public static global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location CreateFromDiscriminatorValue(IParseNode parseNode)
            {
                if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
                var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
                var result = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody.InviteesPostRequestBody_location();
                if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember1 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember1();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember10 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember10();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember2 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember2();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember3 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember3();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember4 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember4();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember5 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember5();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember6 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember6();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember7 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember7();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember8 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember8();
                }
                else if("".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
                {
                    result.InviteesPostRequestBodyLocationMember9 = new global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember9();
                }
                return result;
            }
            /// <summary>
            /// The deserialization information for the current model
            /// </summary>
            /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
            public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
            {
                if(InviteesPostRequestBodyLocationMember1 != null)
                {
                    return InviteesPostRequestBodyLocationMember1.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember10 != null)
                {
                    return InviteesPostRequestBodyLocationMember10.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember2 != null)
                {
                    return InviteesPostRequestBodyLocationMember2.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember3 != null)
                {
                    return InviteesPostRequestBodyLocationMember3.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember4 != null)
                {
                    return InviteesPostRequestBodyLocationMember4.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember5 != null)
                {
                    return InviteesPostRequestBodyLocationMember5.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember6 != null)
                {
                    return InviteesPostRequestBodyLocationMember6.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember7 != null)
                {
                    return InviteesPostRequestBodyLocationMember7.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember8 != null)
                {
                    return InviteesPostRequestBodyLocationMember8.GetFieldDeserializers();
                }
                else if(InviteesPostRequestBodyLocationMember9 != null)
                {
                    return InviteesPostRequestBodyLocationMember9.GetFieldDeserializers();
                }
                return new Dictionary<string, Action<IParseNode>>();
            }
            /// <summary>
            /// Serializes information the current object
            /// </summary>
            /// <param name="writer">Serialization writer to use to serialize this model</param>
            public virtual void Serialize(ISerializationWriter writer)
            {
                if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
                if(InviteesPostRequestBodyLocationMember1 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember1>(null, InviteesPostRequestBodyLocationMember1);
                }
                else if(InviteesPostRequestBodyLocationMember10 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember10>(null, InviteesPostRequestBodyLocationMember10);
                }
                else if(InviteesPostRequestBodyLocationMember2 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember2>(null, InviteesPostRequestBodyLocationMember2);
                }
                else if(InviteesPostRequestBodyLocationMember3 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember3>(null, InviteesPostRequestBodyLocationMember3);
                }
                else if(InviteesPostRequestBodyLocationMember4 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember4>(null, InviteesPostRequestBodyLocationMember4);
                }
                else if(InviteesPostRequestBodyLocationMember5 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember5>(null, InviteesPostRequestBodyLocationMember5);
                }
                else if(InviteesPostRequestBodyLocationMember6 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember6>(null, InviteesPostRequestBodyLocationMember6);
                }
                else if(InviteesPostRequestBodyLocationMember7 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember7>(null, InviteesPostRequestBodyLocationMember7);
                }
                else if(InviteesPostRequestBodyLocationMember8 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember8>(null, InviteesPostRequestBodyLocationMember8);
                }
                else if(InviteesPostRequestBodyLocationMember9 != null)
                {
                    writer.WriteObjectValue<global::Soenneker.Calendly.OpenApiClient.Invitees.InviteesPostRequestBody_locationMember9>(null, InviteesPostRequestBodyLocationMember9);
                }
            }
        }
    }
}
#pragma warning restore CS0618
