// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Calendly.OpenApiClient.Invitees
{
    /// <summary>The event location is a Microsoft Teams conference</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum InviteesPostRequestBody_locationMember7_kind
    {
        [EnumMember(Value = "microsoft_teams_conference")]
        #pragma warning disable CS1591
        Microsoft_teams_conference,
        #pragma warning restore CS1591
    }
}
