// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Calendly.OpenApiClient.Models;
using Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Calendly.OpenApiClient.Routing_form_submissions
{
    /// <summary>
    /// Builds and executes requests for operations under \routing_form_submissions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Routing_form_submissionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Calendly.OpenApiClient.routing_form_submissions.item collection</summary>
        /// <param name="position">Unique identifier of the item</param>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Item.WithUuItemRequestBuilder"/></returns>
        public global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Item.WithUuItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("uuid", position);
                return new global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Item.WithUuItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Routing_form_submissionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routing_form_submissions?form={form}{&count*,page_token*,sort*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Routing_form_submissionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/routing_form_submissions?form={form}{&count*,page_token*,sort*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Get a list of Routing Form Submissions for a specified Routing Form.&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `routing_forms:read`&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200400Error">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200401Error">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200403Error">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200404Error">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200500Error">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200?> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder.Routing_form_submissionsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200> GetAsync(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder.Routing_form_submissionsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200400Error.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200401Error.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200403Error.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200404Error.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200500Error.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200>(requestInfo, global::Soenneker.Calendly.OpenApiClient.Models.ListRoutingFormSubmissions200.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Get a list of Routing Form Submissions for a specified Routing Form.&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `routing_forms:read`&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder.Routing_form_submissionsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder.Routing_form_submissionsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Calendly.OpenApiClient.Routing_form_submissions.Routing_form_submissionsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Get a list of Routing Form Submissions for a specified Routing Form.&lt;!-- theme: info --&gt;  &gt; #### Required scopes: `routing_forms:read`&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class Routing_form_submissionsRequestBuilderGetQueryParameters 
        {
            /// <summary>The number of rows to return</summary>
            [QueryParameter("count")]
            public int? Count { get; set; }
            /// <summary>View routing form submissions associated with the routing form&apos;s URI.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("form")]
            public string? Form { get; set; }
#nullable restore
#else
            [QueryParameter("form")]
            public string Form { get; set; }
#endif
            /// <summary>The token to pass to get the next or previous portion of the collection</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("page_token")]
            public string? PageToken { get; set; }
#nullable restore
#else
            [QueryParameter("page_token")]
            public string PageToken { get; set; }
#endif
            /// <summary>&quot;Order results by the specified field and direction. Accepts comma-separated list of {field}:{direction} values. Supported fields are: created_at. Sort direction is specified as: asc, desc.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("sort")]
            public string? Sort { get; set; }
#nullable restore
#else
            [QueryParameter("sort")]
            public string Sort { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
